### ISSUE TITLE
Validate app name

### ISSUE THREAD

**Issue by chowarth123** [accanto-systems/ignition#12]
Background:
The "app_name" configuration is used when creating kafka topics and kafka topics have limitations on which characters can be used in topic names.

Desired functionality:
The app name is validated to only allow alphanumeric characters.

**Comment by dvaccarosenna** [comment]
Instead we will remove any incompatible characters from the app_name when producing the topic name. This means the app name remains fairly unrestricted, as it's supposed to be decorative.
