### ISSUE TITLE
Add support for a Request Queue

### ISSUE THREAD

**Issue by sglover** [accanto-systems/ignition#46]
Currently all driver requests are handled by calling a REST API. This enhancement will provide a request queue that will automatically queue REST API requests (this will be configurable on a per driver type basis), which can then be consumed in whichever way the driver sees fit (an API will be provided to get the request queue, the request queue will have APIs to consume requests).  The request queue will be based on a partitioned Kafka topic (the usage of Kafka is driven by the fact that it is present in the Accanto LM stack)

**Comment by dvaccarosenna** [comment]
Closed by PR #66
